"""Add CENRO jurisdiction to users

Revision ID: 1433c81a5dc4
Revises: 79a7f9dce1f9
Create Date: 2026-09-02 13:54:50.344976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1433c81a5dc4'
down_revision = '79a7f9dce1f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cenro', sa.String(length=100), nullable=True))
        batch_op.drop_constraint(batch_op.f('users_role_check'), type_='check')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('users_role_check'), "role::text = ANY (ARRAY['admin'::character varying, 'field_officer'::character varying, 'normal_user'::character varying]::text[])")
        batch_op.drop_column('cenro')

    # ### end Alembic commands ###
