"""Expand request model

Revision ID: 63d687af03d8
Revises: ea4bec542477
Create Date: 2026-08-25 08:16:27.913317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '63d687af03d8'
down_revision = 'ea4bec542477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('proposed_area_ha', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('contact_number', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('date_submitted', sa.DateTime(), nullable=False))
        batch_op.add_column(sa.Column('date_reviewed', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('review_note', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['reviewed_by'], ['user_id'])
        batch_op.create_foreign_key(None, 'location', ['location_id'], ['location_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('request', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('review_note')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('date_reviewed')
        batch_op.drop_column('date_submitted')
        batch_op.drop_column('contact_number')
        batch_op.drop_column('proposed_area_ha')
        batch_op.drop_column('location_id')

    # ### end Alembic commands ###
