"""add remaining site columns

Revision ID: 73b12566e942
Revises: d434c27c3778
Create Date: 2026-08-20 22:49:30.266399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73b12566e942'
down_revision = 'd434c27c3778'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reforestation_record', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actual_quantity_planted', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('survival_rate', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('date_validated', sa.Date(), nullable=True))

    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('zone_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('loa_contract_code', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('year_contracted', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('area_contracted_ha', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('date_contract_executed', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('date_contract_expiry', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('project_cost_3yr', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('retention_fee_amount_paid', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('retention_fee_date_paid', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('amount_under_land_improvement', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('amount_still_in_cip', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.create_unique_constraint(None, ['site_code'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('amount_still_in_cip')
        batch_op.drop_column('amount_under_land_improvement')
        batch_op.drop_column('retention_fee_date_paid')
        batch_op.drop_column('retention_fee_amount_paid')
        batch_op.drop_column('project_cost_3yr')
        batch_op.drop_column('date_contract_expiry')
        batch_op.drop_column('date_contract_executed')
        batch_op.drop_column('area_contracted_ha')
        batch_op.drop_column('year_contracted')
        batch_op.drop_column('loa_contract_code')
        batch_op.drop_column('zone_type')
        batch_op.drop_column('site_code')

    with op.batch_alter_table('reforestation_record', schema=None) as batch_op:
        batch_op.drop_column('date_validated')
        batch_op.drop_column('survival_rate')
        batch_op.drop_column('actual_quantity_planted')
    # ### end Alembic commands ###
