"""Add monitoring plots, photo GPS, site boundary

Revision ID: 79a7f9dce1f9
Revises: 63d687af03d8
Create Date: 2026-08-28 08:57:37.499967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a7f9dce1f9'
down_revision = '63d687af03d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('monitoring_plot',
    sa.Column('plot_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('plot_number', sa.Integer(), nullable=False),
    sa.Column('seedlings_alive', sa.Integer(), nullable=False),
    sa.Column('plot_notes', sa.String(length=300), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['monitoring_report.report_id'], ),
    sa.PrimaryKeyConstraint('plot_id')
    )
    with op.batch_alter_table('monitoring_photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plot_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('file_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('photo_type', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('distance_from_centroid_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('flags', sa.String(length=300), nullable=True))
        batch_op.create_foreign_key(None, 'monitoring_plot', ['plot_id'], ['plot_id'])

    with op.batch_alter_table('monitoring_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('site_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('plots_recorded', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('plot_size_sqm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_counted', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('mean_per_plot', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('stdev_per_plot', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('density_per_ha', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('estimated_survivors', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('sampling_intensity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('captured_area_ha', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('area_difference_pct', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('boundary_geojson', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('review_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('reviewed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('date_reviewed', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('submitted_at', sa.DateTime(), nullable=False))
        batch_op.create_foreign_key(None, 'site', ['site_id'], ['site_id'])
        batch_op.create_foreign_key(None, 'users', ['reviewed_by'], ['user_id'])

    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boundary_geojson', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('boundary_area_ha', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('boundary_captured_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_column('boundary_captured_at')
        batch_op.drop_column('boundary_area_ha')
        batch_op.drop_column('boundary_geojson')

    with op.batch_alter_table('monitoring_report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('submitted_at')
        batch_op.drop_column('date_reviewed')
        batch_op.drop_column('reviewed_by')
        batch_op.drop_column('review_note')
        batch_op.drop_column('remarks')
        batch_op.drop_column('boundary_geojson')
        batch_op.drop_column('area_difference_pct')
        batch_op.drop_column('captured_area_ha')
        batch_op.drop_column('sampling_intensity')
        batch_op.drop_column('estimated_survivors')
        batch_op.drop_column('density_per_ha')
        batch_op.drop_column('stdev_per_plot')
        batch_op.drop_column('mean_per_plot')
        batch_op.drop_column('total_counted')
        batch_op.drop_column('plot_size_sqm')
        batch_op.drop_column('plots_recorded')
        batch_op.drop_column('site_id')

    with op.batch_alter_table('monitoring_photo', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('flags')
        batch_op.drop_column('distance_from_centroid_m')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')
        batch_op.drop_column('photo_type')
        batch_op.drop_column('file_hash')
        batch_op.drop_column('plot_id')

    op.drop_table('monitoring_plot')
    # ### end Alembic commands ###
