"""Add site characteristics and species tolerance ranges

Revision ID: 8224fb89b779
Revises: 73b12566e942
Create Date: 2026-08-23 08:14:06.656615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8224fb89b779'
down_revision = '73b12566e942'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('elevation_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('avg_temp_c', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('annual_rainfall_mm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('soil_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('soil_texture', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('agro_ecological_zone', sa.String(length=50), nullable=True))

    with op.batch_alter_table('monitoring_photo', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_monitoring_photo_gps_point'), postgresql_using='gist')
        batch_op.drop_column('gps_point')

    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_site_land_map_boundary'), postgresql_using='gist')
        batch_op.drop_column('land_map_boundary')

    with op.batch_alter_table('tree_specie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_rainfall_mm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_rainfall_mm', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('min_elevation_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_elevation_m', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('min_temp_c', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('max_temp_c', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('preferred_soil', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('is_reference', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tree_specie', schema=None) as batch_op:
        batch_op.drop_column('is_reference')
        batch_op.drop_column('source')
        batch_op.drop_column('preferred_soil')
        batch_op.drop_column('max_temp_c')
        batch_op.drop_column('min_temp_c')
        batch_op.drop_column('max_elevation_m')
        batch_op.drop_column('min_elevation_m')
        batch_op.drop_column('max_rainfall_mm')
        batch_op.drop_column('min_rainfall_mm')

    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('land_map_boundary', sa.NullType(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('idx_site_land_map_boundary'), ['land_map_boundary'], unique=False, postgresql_using='gist')

    with op.batch_alter_table('monitoring_photo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gps_point', sa.NullType(), autoincrement=False, nullable=True))
        batch_op.create_index(batch_op.f('idx_monitoring_photo_gps_point'), ['gps_point'], unique=False, postgresql_using='gist')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('agro_ecological_zone')
        batch_op.drop_column('soil_texture')
        batch_op.drop_column('soil_type')
        batch_op.drop_column('annual_rainfall_mm')
        batch_op.drop_column('avg_temp_c')
        batch_op.drop_column('elevation_m')
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('username', name=op.f('user_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
