"""Add boundary publication workflow

Revision ID: b524485e8830
Revises: 1433c81a5dc4
Create Date: 2026-09-02 20:49:24.376689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b524485e8830'
down_revision = '1433c81a5dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('monitoring_report', schema=None) as batch_op:
        batch_op.add_column(sa.Column('publication_status', sa.String(length=30), server_default='Not Applicable', nullable=False))
        batch_op.add_column(sa.Column('published_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('published_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('publication_note', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['published_by'], ['user_id'])

    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boundary_published', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('boundary_published_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('boundary_published_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('boundary_source_report_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['boundary_published_by'], ['user_id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_role_check'), type_='check')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_check_constraint(batch_op.f('users_role_check'), "role::text = ANY (ARRAY['superadmin'::character varying, 'admin'::character varying, 'field_officer'::character varying, 'normal_user'::character varying]::text[])")

    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('boundary_source_report_id')
        batch_op.drop_column('boundary_published_at')
        batch_op.drop_column('boundary_published_by')
        batch_op.drop_column('boundary_published')

    with op.batch_alter_table('monitoring_report', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('publication_note')
        batch_op.drop_column('published_at')
        batch_op.drop_column('published_by')
        batch_op.drop_column('publication_status')

    # ### end Alembic commands ###
