"""add DENR site info columns

Revision ID: d434c27c3778
Revises: 
Create Date: 2026-08-18 02:40:18.609580

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd434c27c3778'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.add_column(sa.Column('penro', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cenro', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('congressional_district', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('land_classification', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('major_land_use', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('contact_person', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('component', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('commodity', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site', schema=None) as batch_op:
        batch_op.drop_column('commodity')
        batch_op.drop_column('component')
        batch_op.drop_column('contact_person')
        batch_op.drop_column('major_land_use')
        batch_op.drop_column('land_classification')
        batch_op.drop_column('congressional_district')
        batch_op.drop_column('cenro')
        batch_op.drop_column('penro')

    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('password_hash', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('user_pkey')),
    sa.UniqueConstraint('username', name=op.f('user_username_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    # ### end Alembic commands ###
