"""Add coastal exposure and salinity requirement

Revision ID: ea4bec542477
Revises: 8224fb89b779
Create Date: 2026-08-24 05:33:12.622261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea4bec542477'
down_revision = '8224fb89b779'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coastal_exposure', sa.Integer(), nullable=True))

    with op.batch_alter_table('tree_specie', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salinity_requirement', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tree_specie', schema=None) as batch_op:
        batch_op.drop_column('salinity_requirement')

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_column('coastal_exposure')

    # ### end Alembic commands ###
